version: '3.9'

services:
    bugcrowd-webhook-manager:
        build: .
        volumes:
            - ./:/app
        env_file:
            - .env
        ports:
            - 3000:3000
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.bugcrowd-webhook-manager.entrypoints=web, websecure"
            - "traefik.http.routers.bugcrowd-webhook-manager.rule=Host(`${MY_HOST}`)"
            - "traefik.http.routers.bugcrowd-webhook-manager.tls.certresolver=myresolver"
            - "traefik.http.routers.bugcrowd-webhook-manager.tls.domains[0].main=${MY_HOST}"
            - "traefik.http.services.bugcrowd-webhook-manager.loadbalancer.server.port=3000"
    traefik:
        image: "traefik:v2.8"
        container_name: "traefik"
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
            - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
            - "--certificatesresolvers.myresolver.acme.email=${MY_EMAIL}"
            - "--certificatesresolvers.myresolver.acme.storage=/shared/acme.json"
        ports:
            - "80:80"
            - "443:443"
            # - "8080:8080" # Traefik dashboard
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./shared:/shared"
